import { User, Meal, MealPlan, NutritionGoal, HealthMetric, DailyLog } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Trần Minh Khoa',
  email: 'khoa@example.com',
  avatar: '/avatars/user.jpg',
  age: 28,
  weight: 72,
  height: 175,
  gender: 'male',
  dietaryPreferences: ['Vietnamese', 'Low-Calorie'],
  allergies: ['Shellfish'],
};

export const mockMeals: Meal[] = [
  {
    id: '1',
    name: 'Phở Gà',
    description: 'Traditional Vietnamese chicken pho with rice noodles',
    ingredients: ['Chicken breast', 'Rice noodles', 'Broth', 'Herbs', 'Lime'],
    servings: 1,
    prepTime: 15,
    cookTime: 45,
    cuisine: 'Vietnamese',
    tags: ['soup', 'traditional', 'low-calorie'],
    nutrition: {
      calories: 350,
      protein: 28,
      carbs: 42,
      fat: 8,
      fiber: 2,
      sodium: 1200,
    },
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '2',
    name: 'Cơm Tấm Sườn Nướng',
    description: 'Broken rice with grilled pork chop',
    ingredients: ['Broken rice', 'Pork chop', 'Egg', 'Fish sauce', 'Vegetables'],
    servings: 1,
    prepTime: 10,
    cookTime: 20,
    cuisine: 'Vietnamese',
    tags: ['rice', 'traditional', 'popular'],
    nutrition: {
      calories: 520,
      protein: 35,
      carbs: 55,
      fat: 16,
      fiber: 1,
      sodium: 800,
    },
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '3',
    name: 'Bánh Mì Trứng',
    description: 'Egg Vietnamese sandwich',
    ingredients: ['Baguette', 'Eggs', 'Pâté', 'Pickled vegetables', 'Cilantro'],
    servings: 1,
    prepTime: 5,
    cookTime: 10,
    cuisine: 'Vietnamese',
    tags: ['sandwich', 'breakfast', 'quick'],
    nutrition: {
      calories: 380,
      protein: 14,
      carbs: 52,
      fat: 14,
      fiber: 2,
      sodium: 950,
    },
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '4',
    name: 'Gỏi Cuốn Tôm',
    description: 'Shrimp spring rolls with peanut sauce',
    ingredients: ['Rice paper', 'Shrimp', 'Lettuce', 'Herbs', 'Peanut sauce'],
    servings: 2,
    prepTime: 20,
    cookTime: 0,
    cuisine: 'Vietnamese',
    tags: ['appetizer', 'fresh', 'healthy'],
    nutrition: {
      calories: 220,
      protein: 18,
      carbs: 20,
      fat: 8,
      fiber: 2,
      sodium: 600,
    },
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '5',
    name: 'Cơm Rang Chiên',
    description: 'Fried rice with vegetables',
    ingredients: ['Cooked rice', 'Eggs', 'Mixed vegetables', 'Garlic', 'Fish sauce'],
    servings: 1,
    prepTime: 5,
    cookTime: 15,
    cuisine: 'Vietnamese',
    tags: ['rice', 'vegetarian-option', 'quick'],
    nutrition: {
      calories: 420,
      protein: 14,
      carbs: 56,
      fat: 14,
      fiber: 2,
      sodium: 850,
    },
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
];

export const mockNutritionGoal: NutritionGoal = {
  userId: '1',
  dailyCalories: 2000,
  proteinPercentage: 30,
  carbsPercentage: 45,
  fatPercentage: 25,
  waterIntakeLiters: 2.5,
};

export const mockDailyLog: DailyLog = {
  id: '1',
  userId: '1',
  date: new Date(),
  meals: [mockMeals[0], mockMeals[1]],
  totalNutrition: {
    calories: 870,
    protein: 63,
    carbs: 97,
    fat: 24,
    fiber: 3,
    sodium: 2000,
  },
  waterIntake: 1.8,
  notes: 'Good nutrition intake today',
};

export const mockHealthMetrics: HealthMetric[] = [
  {
    userId: '1',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    weight: 75,
    bmi: 24.5,
    bloodPressure: '120/80',
  },
  {
    userId: '1',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    weight: 74.5,
    bmi: 24.3,
    bloodPressure: '118/78',
  },
  {
    userId: '1',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    weight: 74,
    bmi: 24.1,
    bloodPressure: '119/79',
  },
  {
    userId: '1',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    weight: 73.5,
    bmi: 23.9,
    bloodPressure: '117/77',
  },
  {
    userId: '1',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    weight: 73,
    bmi: 23.7,
    bloodPressure: '118/78',
  },
  {
    userId: '1',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    weight: 72.5,
    bmi: 23.5,
    bloodPressure: '120/80',
  },
  {
    userId: '1',
    date: new Date(),
    weight: 72,
    bmi: 23.3,
    bloodPressure: '119/79',
  },
];
